apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-usb-storage-config
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /etc/modprobe.d/usb-storage.conf
        mode: 0600
        overwrite: true
        contents:
          source: data:text/plain;base64,aW5zdGFsbCB1c2Itc3RvcmFnZSAvYmluL2ZhbHNlCmJsYWNrbGlzdCB1c2Itc3RvcmFnZQ==
