apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-usbguard-daemon-rules-config
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /etc/usbguard/usbguard-daemon.conf
        mode: 0600
        overwrite: true
        contents:
          source: data:;base64,IyBSdWxlIHNldCBmaWxlIHBhdGguClJ1bGVGaWxlPS9ldGMvdXNiZ3VhcmQvcnVsZXMuY29uZgoKIyBSdWxlIHNldCBmb2xkZXIgcGF0aC4KUnVsZUZvbGRlcj0vZXRjL3VzYmd1YXJkL3J1bGVzLmQvCgojIEltcGxpY2l0IHBvbGljeSB0YXJnZXQuCkltcGxpY2l0UG9saWN5VGFyZ2V0PWJsb2NrCgojIFByZXNlbnQgZGV2aWNlIHBvbGljeS4KUHJlc2VudERldmljZVBvbGljeT1hcHBseS1wb2xpY3kKCiMgUHJlc2VudCBjb250cm9sbGVyIHBvbGljeS4KUHJlc2VudENvbnRyb2xsZXJQb2xpY3k9a2VlcAoKIyBJbnNlcnRlZCBkZXZpY2UgcG9saWN5LgpJbnNlcnRlZERldmljZVBvbGljeT1hcHBseS1wb2xpY3kKCiMgUmVzdG9yZSBjb250cm9sbGVyIGRldmljZSBzdGF0ZS4KUmVzdG9yZUNvbnRyb2xsZXJEZXZpY2VTdGF0ZT1mYWxzZQoKIyBEZXZpY2UgTWFuYWdlciBiYWNrZW5kCkRldmljZU1hbmFnZXJCYWNrZW5kPXVldmVudAoKIyBVc2VycyBhbGxvd2VkIHRvIHVzZSB0aGUgSVBDIGludGVyZmFjZS4KSVBDQWxsb3dlZFVzZXJzPXJvb3QKCiMgR3JvdXBzIGFsbG93ZWQgdG8gdXNlIHRoZSBJUEMgaW50ZXJmYWNlLgpJUENBbGxvd2VkR3JvdXBzPXdoZWVsCgojIElQQyBhY2Nlc3MgY29udHJvbCBkZWZpbml0aW9uIGZpbGVzIHBhdGguCklQQ0FjY2Vzc0NvbnRyb2xGaWxlcz0vZXRjL3VzYmd1YXJkL0lQQ0FjY2Vzc0NvbnRyb2wuZC8KCiMgR2VuZXJhdGUgZGV2aWNlIHNwZWNpZmljIHJ1bGVzIGluY2x1ZGluZyB0aGUgdmlhNTAyCiMgYXR0cmlidXRlLgpEZXZpY2VSdWxlc1dpdGhQb3J0PWZhbHNlCgojIFVTQkd1YXJkIEF1ZGl0IGV2ZW50cyBsb2cgYmFja2VuZAojICogRmlsZUF1ZGl0IC0gTG9nIGF1ZGl0IGV2ZW50cyBpbnRvIGEgZmlsZSBzcGVjaWZpZWQgYnkKIyAgICAgICAgICAgICAgICAgICAgQXVkaXRGaWxlUGF0aCBzZXR0aW5nIChzZWUgYmVsb3cpCiMgICogTGludXhBdWRpdCAtIExvZyBhdWRpdCBldmVudHMgdXNpbmcgdGhlIExpbnV4IEF1ZGl0IHN1YnN5c3RlbSAodXNpbmcgYXVkaXRfbG9nX3VzZXJfbWVzc2FnZSkKQXVkaXRCYWNrZW5kPUxpbnV4QXVkaXQKCiMgVVNCR3VhcmQgYXVkaXQgZXZlbnRzIGxvZyBmaWxlIHBhdGguCkF1ZGl0RmlsZVBhdGg9L3Zhci9sb2cvdXNiZ3VhcmQvdXNiZ3VhcmQtYXVkaXQubG9nCg==
